const GET_IMAGES_REQUEST = 'GET_IMAGES_REQUEST'
const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS'
const GET_IMAGES_FAIL = 'GET_IMAGES_FAIL'

const URL_TWITTER = `https://twitter.com`
const URL_INSTAGRAM = `https://www.instagram.com`

export {
  GET_IMAGES_REQUEST,
  GET_IMAGES_SUCCESS,
  GET_IMAGES_FAIL,
  URL_TWITTER,
  URL_INSTAGRAM,
}
