const GET_IMAGES_REQUEST = 'GET_IMAGES_REQUEST'
const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS'
const GET_IMAGES_FAIL = 'GET_IMAGES_FAIL'

export { GET_IMAGES_REQUEST, GET_IMAGES_SUCCESS, GET_IMAGES_FAIL }
